const blutooth = [
    {
        id: '28',
        item_image: 'item-category/blutooth/i12 color earbuds.jpeg',
        item_info: 'Color Box earbuds(Without Guaranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '229',
        actual_price: '300',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '29',
        item_image: 'item-category/blutooth/i-12 earbuds.webp',
        item_info: 'i-12 Earbuds (Without Guaranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '199',
        actual_price: '300',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '30',
        item_image: 'item-category/blutooth/anc black-original earbuds.jpeg',
        item_info: 'ANC-Black imported Earbuds with 3 months Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '799',
        actual_price: '1500',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '31',
        item_image: 'item-category/blutooth/anc white blutooth.jpeg',
        item_info: 'ANC-White Earbuds (Without Guaranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '249',
        actual_price: '350',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '32',
        item_image: 'item-category/blutooth/boat extra battery neckband.jpeg',
        item_info: 'Boat Neckback High Qualtiy with Extra Backup (6 Months warranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '799',
        actual_price: '1400',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '33',
        item_image: 'item-category/blutooth/boat transparnt-neckband.jpeg',
        item_info: 'Boat Transparent Neckband (3 Month Warranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '449',
        actual_price: '800',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '34',
        item_image: 'item-category/blutooth/m10 earbuds.webp',
        item_info: 'Earbuds with Torch+Powerbank (Without Guaranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '249',
        actual_price: '350',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '35',
        item_image: 'item-category/blutooth/noise earbuds.webp',
        item_info: 'noise Earbuds High Quality (6 Month Warranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '799',
        actual_price: '1300',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '36',
        item_image: 'item-category/blutooth/microphone1.webp',
        item_info: 'Voice Recording Single Mic',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '349',
        actual_price: '500',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '37',
        item_image: 'item-category/blutooth/pro transparent earbuds.jpeg',
        item_info: 'Transparent Earbuds (Without Guaranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '299',
        actual_price: '600',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '38',
        item_image: 'item-category/blutooth/realme neckband.jpeg',
        item_info: 'realme Neckband (6 Month Warranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '799',
        actual_price: '1400',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '39',
        item_image: 'item-category/blutooth/sh12 headphone.jpeg',
        item_info: 'SH-12 HeadPhone (without Guaranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '349',
        actual_price: '500',
        discount: '30',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '40',
        item_image: 'item-category/blutooth/transparent earbuds 2.webp',
        item_info: 'Transparent High Quality Earbuds (Without Guaranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '249',
        actual_price: '350',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '41',
        item_image: 'item-category/blutooth/transparent earbuds.webp',
        item_info: 'Transparent Earbuds (Without Guaranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '229',
        actual_price: '450',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '139',
        item_image: 'item-category/blutooth/1+ earbuds.png',
        item_info: '1+ Earbud High Quality (6 Month Warranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '729',
        actual_price: '1200',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
   
    {
        id: '140',
        item_image: 'item-category/blutooth/boat-transparent earbuds.png',
        item_info: 'Boat Transparent High Quality Earbud(6 Month Warranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '729',
        actual_price: '1200',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '161',
        item_image: 'item-category/blutooth/BOAT_NECKBAND_60HRS.jpeg',
        item_info: 'Boat 60Hrs High Bass Neckband(6 Month Warranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '449',
        actual_price: '900',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '162',
        item_image: 'item-category/blutooth/BOAT_NECKBAND_500HRS.jpeg',
        item_info: 'Boat 500Hrs Battery Backup High Bass Neckband(6 Month Warranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '729',
        actual_price: '1200',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '163',
        item_image: 'item-category/blutooth/JBL_NECKBAND_500HRS.jpeg',
        item_info: 'JBL 500Hrs Battery Backup High Bass Neckband(6 Month Warranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '729',
        actual_price: '1200',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '164',
        item_image: 'item-category/blutooth/SOROO_IPODS-10_EARBUDS.jpeg',
        item_info: 'SOROO  STEREO IPODS-10 High Quality Earbud(6 Month Warranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '729',
        actual_price: '1200',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '166',
        item_image: 'item-category/blutooth/og_anc_earbuds.webp',
        item_info: 'Original Buds with warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '999',
        actual_price: '2000',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    
]