const blutooth = [
    {
        id: '28',
        item_image: 'item-category/blutooth/i12 color earbuds.jpeg',
        item_info: 'FAST CHARGING 65W DATACABLE WITH 6 MONTH WARRANTY',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '229',
        actual_price: '300',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '29',
        item_image: 'item-category/blutooth/i-12 earbuds.webp',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '199',
        actual_price: '300',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '30',
        item_image: 'item-category/blutooth/anc black-original earbuds.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '799',
        actual_price: '1500',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '31',
        item_image: 'item-category/blutooth/anc white blutooth.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '249',
        actual_price: '350',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '32',
        item_image: 'item-category/blutooth/boat extra battery neckband.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '799',
        actual_price: '1400',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '33',
        item_image: 'item-category/blutooth/boat transparnt-neckband.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '449',
        actual_price: '800',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '34',
        item_image: 'item-category/blutooth/m10 earbuds.webp',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '249',
        actual_price: '350',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '35',
        item_image: 'item-category/blutooth/noise earbuds.webp',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '799',
        actual_price: '1300',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '36',
        item_image: 'item-category/blutooth/microphone1.webp',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '349',
        actual_price: '500',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '37',
        item_image: 'item-category/blutooth/pro transparent earbuds.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '299',
        actual_price: '600',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '38',
        item_image: 'item-category/blutooth/realme neckband.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '799',
        actual_price: '1400',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '39',
        item_image: 'item-category/blutooth/sh12 headphone.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '349',
        actual_price: '500',
        discount: '30',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '40',
        item_image: 'item-category/blutooth/transparent earbuds 2.webp',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '249',
        actual_price: '350',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '41',
        item_image: 'item-category/blutooth/transparent earbuds.webp',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '229',
        actual_price: '450',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '139',
        item_image: 'item-category/blutooth/1+ earbuds.png',
        item_info: '1+ Earbud',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '729',
        actual_price: '1200',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
   
    {
        id: '140',
        item_image: 'item-category/blutooth/boat-transparent earbuds.png',
        item_info: 'Boat Transparent Earbud',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '729',
        actual_price: '1200',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    
]