const chargers = [
    {
        id: '12',
        item_image: 'item-category/charger/2.1A-vivo charger.webp',
        item_info: 'Vivo, Oppo Original Charger with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '129',
        actual_price: '200',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '13',
        item_image: 'item-category/charger/20W mini dash.jpeg',
        item_info: 'Realme 20W Mini Dash Charger with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '199',
        actual_price: '350',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '14',
        item_image: 'item-category/charger/25Wdash charger.webp',
        item_info: '45W Vivo/Oppo/Samsung Charger with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '249',
        actual_price: '450',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '15',
        item_image: 'item-category/charger/30W charger.jpeg',
        item_info: '30 W Fast Charger with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '229',
        actual_price: '500',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '16',
        item_image: 'item-category/charger/45W charger.webp',
        item_info: '45W Vivo Charger with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '249',
        actual_price: '600',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '17',
        item_image: 'item-category/charger/85W charger.jpeg',
        item_info: '85W Super Fast Charger with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '349',
        actual_price: '700',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '18',
        item_image: 'item-category/charger/apple charger-2.jpeg',
        item_info: 'I-Phone Charger Best Quality with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '449',
        actual_price: '900',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '19',
        item_image: 'item-category/charger/apple-charger.jpeg',
        item_info: 'i-Phone Charger with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '559',
        actual_price: '1100',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '20',
        item_image: 'item-category/charger/car charger.webp',
        item_info: 'Car Charger with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '229',
        actual_price: '400',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '21',
        item_image: 'item-category/charger/sam-doc.webp',
        item_info: '2.1A Samsung Orginal Charger with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '129',
        actual_price: '250',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '22',
        item_image: 'item-category/charger/sam-pd charger.jpeg',
        item_info: '25W Samsung PD-Charger with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '499',
        actual_price: '800',
        discount: '60',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '23',
        item_image: 'item-category/charger/ubon transparent-charger.webp',
        item_info: 'Ubon 25W Transparent Charger with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '229',
        actual_price: '350',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '24',
        item_image: 'item-category/charger/vivo 100 OG.jpeg',
        item_info: 'Vivo 44W original Fast Charger with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '599',
        actual_price: '1200',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '151',
        item_image: 'item-category/charger/MI_44W_TRAVEL_CHARGER.jpeg',
        item_info: 'MI 40W Charger with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '249',
        actual_price: '500',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '152',
        item_image: 'item-category/charger/OPPO_40W_TRAVEL_CHARGER.jpeg',
        item_info: 'OPPO 40W Charger with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '249',
        actual_price: '500',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '153',
        item_image: 'item-category/charger/SAMSUNG_25W_PD_CHARGER.jpeg',
        item_info: 'SAMSUNG 25W PD original Fast Charger with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '499',
        actual_price: '1200',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '154',
        item_image: 'item-category/charger/SAMSUNG_85W_SUPER_FAST_CHARGER.jpeg',
        item_info: 'SAMSUNG 85W Fast Charger with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '399',
        actual_price: '800',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '155',
        item_image: 'item-category/charger/SOROO_18W_FAST_CHARGER.jpeg',
        item_info: 'SOROO 18W Fast Charger with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '299',
        actual_price: '450',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '156',
        item_image: 'item-category/charger/SOROO_85W_SUPER_FAST_CHARGER.jpeg',
        item_info: 'SOROO 85W SUPER Fast Charger with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '499',
        actual_price: '1000',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '157',
        item_image: 'item-category/charger/UBON_15W_CHARGER.jpeg',
        item_info: 'UBOB 15W Charger with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '199',
        actual_price: '400',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
]