const chargers = [
    {
        id:'01',
        item_image: 'item-category/charger/2.1A-vivo charger.webp',
        item_info:'FAST CHARGING 65W DATACABLE WITH 6 MONTH WARRANTY',
        seller:'Harry',
        delivery_date:'15-06-2024',
        rating: '4.5',
        current_price:'300',
        actual_price:'3000',
        discount:'90',
        delivery:'40',
        offer:'Bank Offer'
    },
    {
        id:'01',
        item_image: 'item-category/charger/20W mini dash.jpeg',
        item_info:'Men Printed Round Neck Polyester Black T-Shirt',
        seller:'Harry',
        delivery_date:'15-06-2024',
        rating: '4.5',
        current_price:'300',
        actual_price:'3000',
        discount:'90',
        delivery:'40',
        offer:'Bank Offer'
    },
    {
        id:'01',
        item_image: 'item-category/charger/25Wdash charger.webp',
        item_info:'Men Printed Round Neck Polyester Black T-Shirt',
        seller:'Harry',
        delivery_date:'15-06-2024',
        rating: '4.5',
        current_price:'300',
        actual_price:'3000',
        discount:'90',
        delivery:'40',
        offer:'Bank Offer'
    },
    {
        id:'01',
        item_image: 'item-category/charger/30W charger.jpeg',
        item_info:'Men Printed Round Neck Polyester Black T-Shirt',
        seller:'Harry',
        delivery_date:'15-06-2024',
        rating: '4.5',
        current_price:'300',
        actual_price:'3000',
        discount:'90',
        delivery:'40',
        offer:'Bank Offer'
    },
    {
        id:'01',
        item_image: 'item-category/charger/45W charger.webp',
        item_info:'Men Printed Round Neck Polyester Black T-Shirt',
        seller:'Harry',
        delivery_date:'15-06-2024',
        rating: '4.5',
        current_price:'300',
        actual_price:'3000',
        discount:'90',
        delivery:'40',
        offer:'Bank Offer'
    },
    {
        id:'01',
        item_image: 'item-category/charger/85W charger.jpeg',
        item_info:'Men Printed Round Neck Polyester Black T-Shirt',
        seller:'Harry',
        delivery_date:'15-06-2024',
        rating: '4.5',
        current_price:'300',
        actual_price:'3000',
        discount:'90',
        delivery:'40',
        offer:'Bank Offer'
    },
    {
        id:'01',
        item_image: 'item-category/charger/apple charger-2.jpeg',
        item_info:'Men Printed Round Neck Polyester Black T-Shirt',
        seller:'Harry',
        delivery_date:'15-06-2024',
        rating: '4.5',
        current_price:'300',
        actual_price:'3000',
        discount:'90',
        delivery:'40',
        offer:'Bank Offer'
    },
    {
        id:'01',
        item_image: 'item-category/charger/apple-charger.jpeg',
        item_info:'Men Printed Round Neck Polyester Black T-Shirt',
        seller:'Harry',
        delivery_date:'15-06-2024',
        rating: '4.5',
        current_price:'300',
        actual_price:'3000',
        discount:'90',
        delivery:'40',
        offer:'Bank Offer'
    },
    {
        id:'01',
        item_image: 'item-category/charger/car charger.webp',
        item_info:'Men Printed Round Neck Polyester Black T-Shirt',
        seller:'Harry',
        delivery_date:'15-06-2024',
        rating: '4.5',
        current_price:'300',
        actual_price:'3000',
        discount:'90',
        delivery:'40',
        offer:'Bank Offer'
    },
    {
        id:'01',
        item_image: 'item-category/charger/sam-doc.webp',
        item_info:'Men Printed Round Neck Polyester Black T-Shirt',
        seller:'Harry',
        delivery_date:'15-06-2024',
        rating: '4.5',
        current_price:'300',
        actual_price:'3000',
        discount:'90',
        delivery:'40',
        offer:'Bank Offer'
    },
    {
        id:'01',
        item_image: 'item-category/charger/sam-pd charger.jpeg',
        item_info:'Men Printed Round Neck Polyester Black T-Shirt',
        seller:'Harry',
        delivery_date:'15-06-2024',
        rating: '4.5',
        current_price:'300',
        actual_price:'3000',
        discount:'90',
        delivery:'40',
        offer:'Bank Offer'
    },
    {
        id:'01',
        item_image: 'item-category/charger/ubon transparent-charger.webp',
        item_info:'Men Printed Round Neck Polyester Black T-Shirt',
        seller:'Harry',
        delivery_date:'15-06-2024',
        rating: '4.5',
        current_price:'300',
        actual_price:'3000',
        discount:'90',
        delivery:'40',
        offer:'Bank Offer'
    },
    {
        id:'01',
        item_image: 'item-category/charger/vivo 100 OG.jpeg',
        item_info:'Men Printed Round Neck Polyester Black T-Shirt',
        seller:'Harry',
        delivery_date:'15-06-2024',
        rating: '4.5',
        current_price:'300',
        actual_price:'3000',
        discount:'90',
        delivery:'40',
        offer:'Bank Offer'
    },
]