const chargers = [
    {
        id: '12',
        item_image: 'item-category/charger/2.1A-vivo charger.webp',
        item_info: 'FAST CHARGING 65W DATACABLE WITH 6 MONTH WARRANTY',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '129',
        actual_price: '200',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '13',
        item_image: 'item-category/charger/20W mini dash.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '199',
        actual_price: '350',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '14',
        item_image: 'item-category/charger/25Wdash charger.webp',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '249',
        actual_price: '450',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '15',
        item_image: 'item-category/charger/30W charger.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '229',
        actual_price: '500',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '16',
        item_image: 'item-category/charger/45W charger.webp',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '299',
        actual_price: '600',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '17',
        item_image: 'item-category/charger/85W charger.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '349',
        actual_price: '700',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '18',
        item_image: 'item-category/charger/apple charger-2.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '449',
        actual_price: '900',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '19',
        item_image: 'item-category/charger/apple-charger.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '559',
        actual_price: '1100',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '20',
        item_image: 'item-category/charger/car charger.webp',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '229',
        actual_price: '400',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '21',
        item_image: 'item-category/charger/sam-doc.webp',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '129',
        actual_price: '250',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '22',
        item_image: 'item-category/charger/sam-pd charger.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '349',
        actual_price: '800',
        discount: '60',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '23',
        item_image: 'item-category/charger/ubon transparent-charger.webp',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '199',
        actual_price: '350',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '24',
        item_image: 'item-category/charger/vivo 100 OG.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '549',
        actual_price: '1000',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
]