const items = [

    // DATA CABLES DATA

    {
        id: '01',
        item_image: 'item-category/datacable/3 in 1 display cable.jpeg',
        item_info: 'FAST CHARGING 100W DATACABLE WITH 6 MONTH WARRANTY',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '180',
        actual_price: '300',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '02',
        item_image: 'item-category/datacable/3 in 1 ring cable.webp',
        item_info: '3 in 1 DATACABLE WITH 6 MONTH WARRANTY',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '129',
        actual_price: '250',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '03',
        item_image: 'item-category/datacable/datacable.jpeg',
        item_info: '4 in 1 65W Fast Datacable with 6 month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '199',
        actual_price: '350',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '04',
        item_image: 'item-category/datacable/6A cable.jpeg',
        item_info: '6A Fast Charging Datacable with 6 month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '129',
        actual_price: '250',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '05',
        item_image: 'item-category/datacable/25W u&i cable.jpeg',
        item_info: 'u&i 25W Fast Charging Datacable with 6 month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '199',
        actual_price: '300',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '06',
        item_image: 'item-category/datacable/65W cable.webp',
        item_info: '65W Super Fast Charding Datacable with 6 month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '149',
        actual_price: '250',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '07',
        item_image: 'item-category/datacable/85W cable-2.jpeg',
        item_info: '85W Super Fast Charding Datacable with 6 month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '199',
        actual_price: '350',
        discount: '10',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '08',
        item_image: 'item-category/datacable/85W cable.jpeg',
        item_info: '85W Fast Charging Datacable with 6 month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '179',
        actual_price: '350',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '09',
        item_image: 'item-category/datacable/100OG cable.jpeg',
        item_info: '100% original Datacable pack of 2 with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '149',
        actual_price: '150',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '10',
        item_image: 'item-category/datacable/120w cable.webp',
        item_info: '120W Super Fast 2mm Datacable with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '149',
        actual_price: '300',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },

    {
        id: '11',
        item_image: 'item-category/datacable/multi pin cable.jpeg',
        item_info: 'All in One Datacable Box with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '199',
        actual_price: '350',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },

    // CHARGERS DATA LIST

    {
        id: '12',
        item_image: 'item-category/charger/2.1A-vivo charger.webp',
        item_info: 'Vivo, Oppo Original Charger with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '129',
        actual_price: '200',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '13',
        item_image: 'item-category/charger/20W mini dash.jpeg',
        item_info: 'Realme 20W Mini Dash Charger with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '199',
        actual_price: '350',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '14',
        item_image: 'item-category/charger/25Wdash charger.webp',
        item_info: '45W Vivo/Oppo/Samsung Charger with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '249',
        actual_price: '450',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '15',
        item_image: 'item-category/charger/30W charger.jpeg',
        item_info: '30 W Fast Charger with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '229',
        actual_price: '500',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '16',
        item_image: 'item-category/charger/45W charger.webp',
        item_info: '45W Vivo Charger with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '249',
        actual_price: '600',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '17',
        item_image: 'item-category/charger/85W charger.jpeg',
        item_info: '85W Super Fast Charger with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '349',
        actual_price: '700',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '18',
        item_image: 'item-category/charger/apple charger-2.jpeg',
        item_info: 'I-Phone Charger Best Quality with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '449',
        actual_price: '900',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '19',
        item_image: 'item-category/charger/apple-charger.jpeg',
        item_info: 'i-Phone Charger with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '559',
        actual_price: '1100',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '20',
        item_image: 'item-category/charger/car charger.webp',
        item_info: 'Car Charger with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '229',
        actual_price: '400',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '21',
        item_image: 'item-category/charger/sam-doc.webp',
        item_info: '2.1A Samsung Orginal Charger with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '129',
        actual_price: '250',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '22',
        item_image: 'item-category/charger/sam-pd charger.jpeg',
        item_info: '25W Samsung PD-Charger with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '499',
        actual_price: '800',
        discount: '60',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '23',
        item_image: 'item-category/charger/ubon transparent-charger.webp',
        item_info: 'Ubon 25W Transparent Charger with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '229',
        actual_price: '350',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '24',
        item_image: 'item-category/charger/vivo 100 OG.jpeg',
        item_info: 'Vivo 44W original Fast Charger with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '599',
        actual_price: '1200',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },

    // TEMPERS DATA LIST

    {
        id: '25',
        item_image: 'item-category/temper/security glass.jpeg',
        item_info: 'Anti-Static Privacy HD Tempered Glass - Super Quality',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '120',
        actual_price: '180',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '26',
        item_image: 'item-category/temper/super-x-temper.jpeg',
        item_info: 'Super-X HD Tempered Glass - High Quality',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '70',
        actual_price: '100',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '27',
        item_image: 'item-category/temper/uv glass temper.jpeg',
        item_info: 'UV-Privacy Glass Curved-Temper',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '229',
        actual_price: '350',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },

    // BLUTOOTHS DATA LIST

    {
        id: '28',
        item_image: 'item-category/blutooth/i12 color earbuds.jpeg',
        item_info: 'Color Box earbuds(Without Guaranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '229',
        actual_price: '300',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '29',
        item_image: 'item-category/blutooth/i-12 earbuds.webp',
        item_info: 'i-12 Earbuds (Without Guaranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '199',
        actual_price: '300',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '30',
        item_image: 'item-category/blutooth/anc black-original earbuds.jpeg',
        item_info: 'ANC-Black imported Earbuds with 3 months Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '799',
        actual_price: '1500',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '31',
        item_image: 'item-category/blutooth/anc white blutooth.jpeg',
        item_info: 'ANC-White Earbuds (Without Guaranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '249',
        actual_price: '350',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '32',
        item_image: 'item-category/blutooth/boat extra battery neckband.jpeg',
        item_info: 'Boat Neckback High Qualtiy with Extra Backup (6 Months warranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '799',
        actual_price: '1400',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '33',
        item_image: 'item-category/blutooth/boat transparnt-neckband.jpeg',
        item_info: 'Boat Transparent Neckband (3 Month Warranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '449',
        actual_price: '800',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '34',
        item_image: 'item-category/blutooth/m10 earbuds.webp',
        item_info: 'Earbuds with Torch+Powerbank (Without Guaranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '249',
        actual_price: '350',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '35',
        item_image: 'item-category/blutooth/noise earbuds.webp',
        item_info: 'noise Earbuds High Quality (6 Month Warranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '799',
        actual_price: '1300',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '36',
        item_image: 'item-category/blutooth/microphone1.webp',
        item_info: 'Voice Recording Single Mic',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '349',
        actual_price: '500',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '37',
        item_image: 'item-category/blutooth/pro transparent earbuds.jpeg',
        item_info: 'Transparent Earbuds (Without Guaranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '299',
        actual_price: '600',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '38',
        item_image: 'item-category/blutooth/realme neckband.jpeg',
        item_info: 'realme Neckband (6 Month Warranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '799',
        actual_price: '1400',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '39',
        item_image: 'item-category/blutooth/sh12 headphone.jpeg',
        item_info: 'SH-12 HeadPhone (without Guaranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '349',
        actual_price: '500',
        discount: '30',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '40',
        item_image: 'item-category/blutooth/transparent earbuds 2.webp',
        item_info: 'Transparent High Quality Earbuds (Without Guaranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '249',
        actual_price: '350',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '41',
        item_image: 'item-category/blutooth/transparent earbuds.webp',
        item_info: 'Transparent Earbuds (Without Guaranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '229',
        actual_price: '450',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },

    // SMART WATCHES DATA LIST
    {
        id: '42',
        item_image: 'item-category/smartwatch/firebolt-1.jpeg',
        item_info: 'ForeBolt Smart Watch',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '849',
        actual_price: '1300',
        discount: '35',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '43',
        item_image: 'item-category/smartwatch/firebolt-2.jpeg',
        item_info: 'ForeBolt Smart Watch Round Dial',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '949',
        actual_price: '1500',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '44',
        item_image: 'item-category/smartwatch/s8 watch.jpeg',
        item_info: 'S-8 Smart Watch',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '399',
        actual_price: '600',
        discount: '30',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '45',
        item_image: 'item-category/smartwatch/series 9 watch.jpeg',
        item_info: 'S-9 Series Smart Watch',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '449',
        actual_price: '800',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '46',
        item_image: 'item-category/smartwatch/t-10 ulta.jpeg',
        item_info: 'T-10 Ulta Smart Watch',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '599',
        actual_price: '900',
        discount: '35',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '47',
        item_image: 'item-category/smartwatch/t800 ultra.jpeg',
        item_info: 'T-800 Ultra Smart Watch',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '499',
        actual_price: '1000',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '48',
        item_image: 'item-category/smartwatch/smartwatch-180.jpeg',
        item_info: 'Smart Bracelet Watch',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '219',
        actual_price: '300',
        discount: '30',
        delivery: '00',
        offer: 'Bank Offer'
    },

    // SPEAKERS DATA LIST

    {
        id: '49',
        item_image: 'item-category/speakers/tyre-speaker.jpeg',
        item_info: 'Smart & Unique Tyre Speaker with LED',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '649',
        actual_price: '900',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },

    {
        id: '50',
        item_image: 'item-category/speakers/halozan.jpeg',
        item_info: 'Advertise Loud Speaker',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '459',
        actual_price: '600',
        discount: '25',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '51',
        item_image: 'item-category/speakers/light sound bulb.jpeg',
        item_info: 'LED Buld with Sound',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '299',
        actual_price: '450',
        discount: '40',
        delivery: '40',
        offer: 'Bank Offer'
    },
    {
        id: '52',
        item_image: 'item-category/speakers/minispeaker.webp',
        item_info: 'Mini High Bass Speaker',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '249',
        actual_price: '400',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '53',
        item_image: 'item-category/speakers/mz soundbar.jpeg',
        item_info: 'Wound Bar with LED light',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '529',
        actual_price: '700',
        discount: '30',
        delivery: '00',
        offer: 'Bank Offer'
    },

    {
        id: '54',
        item_image: 'item-category/speakers/mz-soundbar-2.jpeg',
        item_info: 'MZ Sound with high Quality bass',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '549',
        actual_price: '800',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '55',
        item_image: 'item-category/speakers/disco-speaker.jpeg',
        item_info: 'Disco Light Speaker',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '289',
        actual_price: '400',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },

    {
        id: '56',
        item_image: 'item-category/speakers/mzspeaker-2.jpeg',
        item_info: 'MZ Speaker with light',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '279',
        actual_price: '400',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '57',
        item_image: 'item-category/speakers/mzspeaker-3.jpeg',
        item_info: 'MZ Speaker High Bass with light',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '299',
        actual_price: '450',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },

    {
        id: '58',
        item_image: 'item-category/speakers/mzspeaker.webp',
        item_info: 'MZ Speaker High Bass with light',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '289',
        actual_price: '400',
        discount: '25',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '59',
        item_image: 'item-category/speakers/speaker mic sound.jpeg',
        item_info: 'Metal Sound with Mic high quality',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '599',
        actual_price: '850',
        discount: '30',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '60',
        item_image: 'item-category/speakers/woodspeaker.webp',
        item_info: 'Wooden Speaker',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '279',
        actual_price: '400',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },

    // BATTERY DATA LIST

    {
        id: '61',
        item_image: 'item-category/battery/drone battery.jpeg',
        item_info: 'Drone Battery (Without Guaranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '299',
        actual_price: '500',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '62',
        item_image: 'item-category/battery/mi 2000 mah powebank.jpeg',
        item_info: 'Mi 20000 Mah Powerbank (6 Month warranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '999',
        actual_price: '1500',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '63',
        item_image: 'item-category/battery/samsung-5c.jpeg',
        item_info: 'Samsung Keypad 5-C battery (6 Month Warranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '129',
        actual_price: '250',
        discount: '45',
        delivery: '00',
        offer: 'Bank Offer'
    },


    // MEMORY CARDS DATA LIST

    {
        id: '64',
        item_image: 'item-category/memorycards/cross-8GB.jpeg',
        item_info: '8GB Cross Memory Card (6 Month Warranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '219',
        actual_price: '350',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },

    // EARPHONES DATA LIST

    {
        id: '65',
        item_image: 'item-category/earphones/sam-earphone.jpeg',
        item_info: 'Samsung Earphone Pack of 2',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '99',
        actual_price: '100',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '66',
        item_image: 'item-category/earphones/boat earphone-50.jpeg',
        item_info: 'Boat Earphone Pack of 2',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '99',
        actual_price: '100',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '67',
        item_image: 'item-category/earphones/akg-earphone.jpeg',
        item_info: 'AKG Earphone high Quality Pack of 1',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '109',
        actual_price: '220',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '68',
        item_image: 'item-category/earphones/earphone-100.jpeg',
        item_info: 'Boat high Quality bass Pack of 1',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '99',
        actual_price: '200',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '69',
        item_image: 'item-category/earphones/realme earphone.jpeg',
        item_info: 'Realme High Quality Bass Earphone',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '99',
        actual_price: '200',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '70',
        item_image: 'item-category/earphones/type-c earphone.jpeg',
        item_info: 'Type-C High Super Earphone',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '99',
        actual_price: '250',
        discount: '60',
        delivery: '00',
        offer: 'Bank Offer'
    },

    //MOBILE COVERS DATA LIST

    {
        id: '71',
        item_image: 'item-category/mobilecover/6dcover.jpeg',
        item_info: '(Pack of 2)6D Imported Mobile Cover ',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '99',
        actual_price: '100',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '72',
        item_image: 'item-category/mobilecover/doll.jpeg',
        item_info: 'Female Mobile Cover',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '129',
        actual_price: '250',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '73',
        item_image: 'item-category/mobilecover/flip-cover.webp',
        item_info: 'Imported Mobile Flip Cover',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '99',
        actual_price: '150',
        discount: '30',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '74',
        item_image: 'item-category/mobilecover/metalringcover.jpeg',
        item_info: 'Metal Ring Imported Mobile Cover',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '149',
        actual_price: '300',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '75',
        item_image: 'item-category/mobilecover/puffcover.jpeg',
        item_info: '(Pack of 2)Puff Mobile Cover',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '150',
        actual_price: '100',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '76',
        item_image: 'item-category/mobilecover/socool.jpeg',
        item_info: 'So-Cool Imported shiny Mobile Cover',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '80',
        actual_price: '100',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },

    // MOBILE STANDS DATA LIST

    {
        id: '77',
        item_image: 'item-category/mobilestand/mobile plug holder.webp',
        item_info: '(Pack of 2) Mobile Charging Stand',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '149',
        actual_price: '300',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '78',
        item_image: 'item-category/mobilestand/mobile premium stand.webp',
        item_info: 'Imported Mobile Stand',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '129',
        actual_price: '250',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '79',
        item_image: 'item-category/mobilestand/mobile round stand.jpeg',
        item_info: 'metalic Round Mobile Stand High Strenth',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '149',
        actual_price: '300',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '80',
        item_image: 'item-category/mobilestand/mobilestand20.jpeg',
        item_info: 'Mobile Stand Non-Metalic',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '29',
        actual_price: '60',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '81',
        item_image: 'item-category/mobilestand/selfie stand with light.jpeg',
        item_info: 'Selfie Stick with light',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '189',
        actual_price: '300',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '82',
        item_image: 'item-category/mobilestand/selfie stand without light.webp',
        item_info: 'Selfie Stick without light',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '169',
        actual_price: '250',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '83',
        item_image: 'item-category/mobilestand/triangle stnad.jpeg',
        item_info: '3-Shape Triangle Mobile Stand',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '15',
        actual_price: '30',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },

    // PEN DRIVE DATA LIST

    {
        id: '84',
        item_image: 'item-category/pendrive/card read small usb.jpeg',
        item_info: 'Card Reader',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '15',
        actual_price: '30',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '85',
        item_image: 'item-category/pendrive/sandisk 64GB pendrive.jpeg',
        item_info: '64GB Sandisk Pendrive (6 Month Warranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '429',
        actual_price: '800',
        discount: '45',
        delivery: '00',
        offer: 'Bank Offer'
    },

    // MOBILE PHONES DATA LIST

    {
        id: '86',
        item_image: 'item-category/mobilephones/sam-B310 E.jpeg',
        item_info: 'Samsung B-310E Mobile with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '1199',
        actual_price: '1600',
        discount: '30',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '87',
        item_image: 'item-category/mobilephones/sam-guru-1200.jpeg',
        item_info: 'Samsung Guru 1200 Single Sim (Without Warranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '899',
        actual_price: '1400',
        discount: '30',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '88',
        item_image: 'item-category/mobilephones/sam-keytone-2 guru.jpeg',
        item_info: 'Samsung Guru1200 Keytone Single sim (6 Month Warranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '999',
        actual_price: '1400',
        discount: '30',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '89',
        item_image: 'item-category/mobilephones/nokia.jpeg',
        item_info: 'Nokia 105 Single Sim UPI Inbuilt (1 Year Warranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '1399',
        actual_price: '1600',
        discount: '30',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '90',
        item_image: 'item-category/mobilephones/nokia 105.jpeg',
        item_info: 'Nokia 105 Dual Sim UPI Inbuilt (1 Year Warranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '1499',
        actual_price: '1800',
        discount: '30',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '91',
        item_image: 'item-category/mobilephones/jio phone.jpeg',
        item_info: 'Jio Phone with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '999',
        actual_price: '1200',
        discount: '20',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '92',
        item_image: 'item-category/mobilephones/flip phone.jpeg',
        item_info: 'Flip Keypad Mobile (without Warranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '1599',
        actual_price: '2000',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },

    // DIWALI LIGHTS DATA LIST

    {
        id: '93',
        item_image: 'item-category/lights/ball-light.webp',
        item_info: 'FAST CHARGING 65W DATACABLE WITH 6 MONTH WARRANTY',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '149',
        actual_price: '250',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '94',
        item_image: 'item-category/lights/cliplight.webp',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '179',
        actual_price: '300',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '95',
        item_image: 'item-category/lights/colorbulb1.webp',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '39',
        actual_price: '60',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '96',
        item_image: 'item-category/lights/colorbulb2.webp',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '79',
        actual_price: '120',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '97',
        item_image: 'item-category/lights/colorbulb3.webp',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '119',
        actual_price: '200',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '98',
        item_image: 'item-category/lights/colorstarlight.webp',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '279',
        actual_price: '3000',
        discount: '90',
        delivery: '40',
        offer: 'Bank Offer'
    },
    {
        id: '99',
        item_image: 'item-category/lights/starlight-warm.webp',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '259',
        actual_price: '3000',
        discount: '90',
        delivery: '40',
        offer: 'Bank Offer'
    },
    {
        id: '100',
        item_image: 'item-category/lights/bottlelight.webp',
        item_info: 'Pack of 4',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '129',
        actual_price: '250',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '101',
        item_image: 'item-category/lights/diya-12.webp',
        item_info: 'Pack of 12',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '149',
        actual_price: '250',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '102',
        item_image: 'item-category/lights/heart-light.jpg',
        item_info: '6+6 Warm white lights Pack of 1',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '249',
        actual_price: '350',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '103',
        item_image: 'item-category/lights/diya-light.webp',
        item_info: '6+6 Warm white lights Pack of 1',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '249',
        actual_price: '350',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '104',
        item_image: 'item-category/lights/led glu strip.webp',
        item_info: 'Multicolor lights Pack of 1',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '229',
        actual_price: '350',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '105',
        item_image: 'item-category/lights/patta light-12ft.webp',
        item_info: '12ft Multicolor running lights Pack of 1',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '249',
        actual_price: '350',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '106',
        item_image: 'item-category/lights/starlight-warm.webp',
        item_info: '6+6 Warm White lights Pack of 1',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '249',
        actual_price: '350',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '107',
        item_image: 'item-category/lights/swastik-light.webp',
        item_info: '6+6 Warm White lights Pack of 1',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '249',
        actual_price: '350',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },


    {
        id: '108',
        item_image: 'item-category/lights/glass light.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '249',
        actual_price: '350',
        discount: '30',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '109',
        item_image: 'item-category/lights/wall-solar light -2.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '249',
        actual_price: '350',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '110',
        item_image: 'item-category/lights/wall-solar-light.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '229',
        actual_price: '350',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '111',
        item_image: 'item-category/lights/torch-129.jpeg',
        item_info: 'High Beam Light',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '149',
        actual_price: '250',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },

    // HOME APPLIANCE DATA LIST

    {
        id: '112',
        item_image: 'item-category/homeappliances/bajaj-invertor-bulb.webp',
        item_info: 'FAST CHARGING 65W DATACABLE WITH 6 MONTH WARRANTY',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '325',
        actual_price: '549',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '113',
        item_image: 'item-category/homeappliances/crompton-invertor-bulb.webp',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '320',
        actual_price: '500',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },

    // SECURITY DATA LIST





    // SMART GADGETS DATA LIST

    {
        id: '114',
        item_image: 'item-category/smartgadgets/cable protector.jpeg',
        item_info: 'Cable Protector Pack of 3',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '50',
        actual_price: '3000',
        discount: '90',
        delivery: '40',
        offer: 'Bank Offer'
    },
    {
        id: '115',
        item_image: 'item-category/smartgadgets/connector1.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '59',
        actual_price: '100',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '116',
        item_image: 'item-category/smartgadgets/connectors4.webp',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '199',
        actual_price: '350',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '117',
        item_image: 'item-category/smartgadgets/dancing cactus.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '249',
        actual_price: '350',
        discount: '30',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '118',
        item_image: 'item-category/smartgadgets/drone.webp',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '1499',
        actual_price: '3000',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '119',
        item_image: 'item-category/smartgadgets/hairdrier.webp',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '299',
        actual_price: '400',
        discount: '30',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '120',
        item_image: 'item-category/smartgadgets/k9 mic.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '329',
        actual_price: '500',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '121',
        item_image: 'item-category/smartgadgets/led usb bulb.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '15',
        actual_price: '30',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '122',
        item_image: 'item-category/smartgadgets/mini projector.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '1499',
        actual_price: '3000',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '123',
        item_image: 'item-category/smartgadgets/moscuto bat-2.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '249',
        actual_price: '500',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '124',
        item_image: 'item-category/smartgadgets/otg 30.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '29',
        actual_price: '60',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '125',
        item_image: 'item-category/smartgadgets/otg-50.webp',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '49',
        actual_price: '100',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '126',
        item_image: 'item-category/smartgadgets/pen stand.jpeg',
        item_info: 'Pen Stand & Writing Pack of 3',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '49',
        actual_price: '100',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '127',
        item_image: 'item-category/smartgadgets/plug hub -10 pin.webp',
        item_info: 'Lady Jointer 10-Pin Switch',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '129',
        actual_price: '200',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '128',
        item_image: 'item-category/smartgadgets/plug hub combo.webp',
        item_info: 'Lady Jointer 10-Pin Switch Pack of 2',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '200',
        actual_price: '300',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '129',
        item_image: 'item-category/smartgadgets/pubg thumb.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '10',
        actual_price: '20',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '130',
        item_image: 'item-category/smartgadgets/sim ejector.jpeg',
        item_info: 'Sim Ejector Pack of 10',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '29',
        actual_price: '100',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '131',
        item_image: 'item-category/smartgadgets/torch mulitpurpose.jpeg',
        item_info: 'Multipurpose Torch',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '149',
        actual_price: '250',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '132',
        item_image: 'item-category/smartgadgets/treamer.jpeg',
        item_info: 'Vintage Treamer Super Quality',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '279',
        actual_price: '500',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '133',
        item_image: 'item-category/smartgadgets/usbhub.webp',
        item_info: '4 in 1 USB Hub Connector Super Quality',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '179',
        actual_price: '300',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '134',
        item_image: 'item-category/smartgadgets/v8 to type c.jpeg',
        item_info: 'V8 to Type-C Connector pack of 1',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '25',
        actual_price: '50',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '135',
        item_image: 'item-category/smartgadgets/vaccumcleaner.webp',
        item_info: 'Vaccum Cleaner Pack of 1',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '279',
        actual_price: '500',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '136',
        item_image: 'item-category/smartgadgets/water bottle temperature.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '199',
        actual_price: '350',
        discount: '30',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '137',
        item_image: 'item-category/smartgadgets/wireless blutooth-2.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '79',
        actual_price: '120',
        discount: '30',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '138',
        item_image: 'item-category/smartgadgets/writing pad.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '89',
        actual_price: '150',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '139',
        item_image: 'item-category/blutooth/1+ earbuds.png',
        item_info: '1+ Earbud High Quality (6 Month Warranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '729',
        actual_price: '1200',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
   
    {
        id: '140',
        item_image: 'item-category/blutooth/boat-transparent earbuds.png',
        item_info: 'Boat Transparent High Quality Earbud(6 Month Warranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '729',
        actual_price: '1200',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '141',
        item_image: 'item-category/computer-accessory/U&i Mouse.png',
        item_info: 'U&i wired Super Quality Mouse',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '219',
        actual_price: '350',
        discount: '30',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '142',
        item_image: 'item-category/datacable/3.8 Turbo Riviera Cable.png',
        item_info: '3.5A Fast Charging Datacable with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '149',
        actual_price: '350',
        discount: '55',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '143',
        item_image: 'item-category/datacable/85W 1+ cable.png',
        item_info: '1+ 85W Fast Changing Datacable with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '179',
        actual_price: '350',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    
    {
        id: '144',
        item_image: 'item-category/datacable/85W Oppo Cable.png',
        item_info: 'Oppo 85W Fast Changing Datacable with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '179',
        actual_price: '350',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '145',
        item_image: 'item-category/datacable/85W Vivo Cable.png',
        item_info: 'Vivo 85W Fast Changing Datacable with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '179',
        actual_price: '350',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '146',
        item_image: 'item-category/memorycards/4GB Balaji Chip.png',
        item_info: 'Balaji Memory Card 4-GB with 1 Year warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '179',
        actual_price: '300',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '147',
        item_image: 'item-category/memorycards/32GB Balaji Chip.png',
        item_info: 'Balaji Memory Card 32-GB with 1 Year warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '249',
        actual_price: '450',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '148',
        item_image: 'item-category/pendrive/Big CardReader.png',
        item_info: 'All in one Card Reader',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '89',
        actual_price: '150',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '149',
        item_image: 'item-category/smartgadgets/RiderLed.png',
        item_info: 'Running Bike LED Light',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '69',
        actual_price: '150',
        discount: '45',
        delivery: '20',
        offer: 'Bank Offer'
    },
    {
        id: '150',
        item_image: 'item-category/computer-accessory/U&i keyboard.webp',
        item_info: 'U&i wired Super Quality Keyboard',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '349',
        actual_price: '500',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },

]