const datacables = [
    {
        id: '01',
        item_image: 'item-category/datacable/3 in 1 display cable.jpeg',
        item_info: 'FAST CHARGING 65W DATACABLE WITH 6 MONTH WARRANTY',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '180',
        actual_price: '300',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '02',
        item_image: 'item-category/datacable/3 in 1 ring cable.webp',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '129',
        actual_price: '250',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '03',
        item_image: 'item-category/datacable/3in1 cable.webp',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '199',
        actual_price: '350',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '04',
        item_image: 'item-category/datacable/6A cable.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '129',
        actual_price: '250',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '05',
        item_image: 'item-category/datacable/25W u&i cable.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '199',
        actual_price: '300',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '06',
        item_image: 'item-category/datacable/65W cable.webp',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '149',
        actual_price: '250',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '07',
        item_image: 'item-category/datacable/85W cable-2.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '199',
        actual_price: '350',
        discount: '10',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '08',
        item_image: 'item-category/datacable/85W cable.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '229',
        actual_price: '350',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '09',
        item_image: 'item-category/datacable/100OG cable.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '99',
        actual_price: '150',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '10',
        item_image: 'item-category/datacable/120w cable.webp',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '149',
        actual_price: '300',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },

    {
        id: '13',
        item_image: 'item-category/datacable/multi pin cable.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '179',
        actual_price: '350',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },


]