const datacables = [
    {
        id: '01',
        item_image: 'item-category/datacable/3 in 1 display cable.jpeg',
        item_info: 'FAST CHARGING 100W DATACABLE WITH 6 MONTH WARRANTY',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '180',
        actual_price: '300',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '02',
        item_image: 'item-category/datacable/3 in 1 ring cable.webp',
        item_info: '3 in 1 DATACABLE WITH 6 MONTH WARRANTY',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '129',
        actual_price: '250',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '03',
        item_image: 'item-category/datacable/datacable.jpeg',
        item_info: '4 in 1 65W Fast Datacable with 6 month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '199',
        actual_price: '350',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '04',
        item_image: 'item-category/datacable/6A cable.jpeg',
        item_info: '6A Fast Charging Datacable with 6 month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '129',
        actual_price: '250',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '05',
        item_image: 'item-category/datacable/25W u&i cable.jpeg',
        item_info: 'u&i 25W Fast Charging Datacable with 6 month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '199',
        actual_price: '300',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '06',
        item_image: 'item-category/datacable/65W cable.webp',
        item_info: '65W Super Fast Charding Datacable with 6 month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '149',
        actual_price: '250',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '07',
        item_image: 'item-category/datacable/85W cable-2.jpeg',
        item_info: '85W Super Fast Charding Datacable with 6 month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '199',
        actual_price: '350',
        discount: '10',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '08',
        item_image: 'item-category/datacable/85W cable.jpeg',
        item_info: '85W Fast Charging Datacable with 6 month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '179',
        actual_price: '350',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '09',
        item_image: 'item-category/datacable/100OG cable.jpeg',
        item_info: '100% original Datacable pack of 2 with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '149',
        actual_price: '150',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '10',
        item_image: 'item-category/datacable/120w cable.webp',
        item_info: '120W Super Fast 2mm Datacable with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '149',
        actual_price: '300',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },

    {
        id: '11',
        item_image: 'item-category/datacable/multi pin cable.jpeg',
        item_info: 'All in One Datacable Box with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '199',
        actual_price: '350',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '142',
        item_image: 'item-category/datacable/3.8 Turbo Riviera Cable.png',
        item_info: '3.5A Fast Charging Datacable with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '149',
        actual_price: '350',
        discount: '55',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '143',
        item_image: 'item-category/datacable/85W 1+ cable.png',
        item_info: '1+ 85W Fast Changing Datacable with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '179',
        actual_price: '350',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    
    {
        id: '144',
        item_image: 'item-category/datacable/85W Oppo Cable.png',
        item_info: 'Oppo 85W Fast Changing Datacable with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '179',
        actual_price: '350',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '145',
        item_image: 'item-category/datacable/85W Vivo Cable.png',
        item_info: 'Vivo 85W Fast Changing Datacable with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '179',
        actual_price: '350',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '158',
        item_image: 'item-category/datacable/3 IN 1_MAGNETIC_CABLE.jpeg',
        item_info: '3 in 1 Magnetic Fast Changing Datacable with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '199',
        actual_price: '400',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '159',
        item_image: 'item-category/datacable/BOAT_44W_CABLE.jpeg',
        item_info: 'Boat 44W Fast Changing Datacable with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '219',
        actual_price: '400',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '160',
        item_image: 'item-category/datacable/U&I_45W_CABLE.jpeg',
        item_info: 'U&I 45W Fast Changing Datacable with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '199',
        actual_price: '350',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },



]