const items = [
    {
        id:'01',
        item_image: 'items/item-1.png',
        item_info:'Men Printed Round Neck Polyester Black T-Shirt',
        seller:'Harry',
        delivery_date:'15-06-2024',
        rating: '4.5',
        current_price:'300',
        actual_price:'3000',
        discount:'90',
        delivery:'40',
        offer:'Bank Offer'
    },

    {
        id:'02',
        item_image: 'items/item-2.png',
        item_info:'Men Printed Round Neck Polyester Black T-Shirt',
        seller:'Manish',
        delivery_date:'16-06-2024',
        rating: '4.5',
        current_price:'1500',
        actual_price:'3000',
        discount:'50',
        delivery:'40',
        offer:'Bank Offer'
    },
    {
        id:'03',
        item_image: 'items/item-3.png',
        item_info:'Men Printed Round Neck Polyester Black T-Shirt',
        seller:'Atishay',
        delivery_date:'17-06-2024',
        rating: '4.5',
        current_price:'300',
        actual_price:'3000',
        discount:'90',
        delivery:'20',
        offer:'Bank Offer'
    },
    {
        id:'04',
        item_image: 'items/item-4.png',
        item_info:'Men Printed Round Neck Polyester Black T-Shirt',
        seller:'Rohit',
        delivery_date:'18-06-2024',
        rating: '4.5',
        current_price:'1500',
        actual_price:'3000',
        discount:'50',
        delivery:'20',
        offer:'Bank Offer'
    },
    {
        id:'05',
        item_image: 'items/item-5.png',
        item_info:'Men Printed Round Neck Polyester Black T-Shirt',
        seller:'Rahul',
        delivery_date:'19-06-2024',
        rating: '4.5',
        current_price:'750',
        actual_price:'1500',
        discount:'50',
        delivery:'40',
        offer:'Bank Offer'
    },
    {
        id:'06',
        item_image: 'items/item-6.png',
        item_info:'Men Printed Round Neck Polyester Black T-Shirt',
        seller:'Pankaj',
        delivery_date:'20-06-2024',
        rating: '4.5',
        current_price:'1000',
        actual_price:'2000',
        discount:'50',
        delivery:'0',
        offer:'Bank Offer'
    },
    {
        id:'07',
        item_image: 'items/item-7.png',
        item_info:'Men Printed Round Neck Polyester Black T-Shirt',
        seller:'Vinod',
        delivery_date:'21-06-2024',
        rating: '4.5',
        current_price:'1500',
        actual_price:'3000',
        discount:'50',
        delivery:'0',
        offer:'Bank Offer'
    },
    {
        id:'08',
        item_image: 'items/item-8.png',
        item_info:'Men Printed Round Neck Polyester Black T-Shirt',
        seller:'Chacha',
        delivery_date:'22-06-2024',
        rating: '4.5',
        current_price:'500',
        actual_price:'1000',
        discount:'50',
        delivery:'0',
        offer:'Bank Offer'
    },
    {
        id:'08',
        item_image: 'items/item-8.png',
        item_info:'Men Printed Round Neck Polyester Black T-Shirt',
        seller:'Chacha',
        delivery_date:'22-06-2024',
        rating: '4.5',
        current_price:'500',
        actual_price:'1000',
        discount:'50',
        delivery:'0',
        offer:'Bank Offer'
    },
    {
        id:'08',
        item_image: 'items/item-8.png',
        item_info:'Men Printed Round Neck Polyester Black T-Shirt',
        seller:'Chacha',
        delivery_date:'22-06-2024',
        rating: '4.5',
        current_price:'500',
        actual_price:'1000',
        discount:'50',
        delivery:'0',
        offer:'Bank Offer'
    },
    {
        id:'08',
        item_image: 'items/item-8.png',
        item_info:'Men Printed Round Neck Polyester Black T-Shirt',
        seller:'Chacha',
        delivery_date:'22-06-2024',
        rating: '4.5',
        current_price:'500',
        actual_price:'1000',
        discount:'50',
        delivery:'0',
        offer:'Bank Offer'
    },
    {
        id:'08',
        item_image: 'items/item-8.png',
        item_info:'Men Printed Round Neck Polyester Black T-Shirt',
        seller:'Chacha',
        delivery_date:'22-06-2024',
        rating: '4.5',
        current_price:'500',
        actual_price:'1000',
        discount:'50',
        delivery:'0',
        offer:'Bank Offer'
    },
    {
        id:'08',
        item_image: 'items/item-8.png',
        item_info:'Men Printed Round Neck Polyester Black T-Shirt',
        seller:'Chacha',
        delivery_date:'22-06-2024',
        rating: '4.5',
        current_price:'500',
        actual_price:'1000',
        discount:'50',
        delivery:'0',
        offer:'Bank Offer'
    },
    {
        id:'08',
        item_image: 'items/item-8.png',
        item_info:'Men Printed Round Neck Polyester Black T-Shirt',
        seller:'Chacha',
        delivery_date:'22-06-2024',
        rating: '4.5',
        current_price:'500',
        actual_price:'1000',
        discount:'50',
        delivery:'0',
        offer:'Bank Offer'
    },
    {
        id:'08',
        item_image: 'items/item-8.png',
        item_info:'Men Printed Round Neck Polyester Black T-Shirt',
        seller:'Chacha',
        delivery_date:'22-06-2024',
        rating: '4.5',
        current_price:'500',
        actual_price:'1000',
        discount:'50',
        delivery:'0',
        offer:'Bank Offer'
    },
    {
        id:'08',
        item_image: 'items/item-8.png',
        item_info:'Men Printed Round Neck Polyester Black T-Shirt',
        seller:'Chacha',
        delivery_date:'22-06-2024',
        rating: '4.5',
        current_price:'500',
        actual_price:'1000',
        discount:'50',
        delivery:'0',
        offer:'Bank Offer'
    },
]