const earphones = [
    {
        id: '65',
        item_image: 'item-category/earphones/sam-earphone.jpeg',
        item_info: 'Samsung Earphone Pack of 2',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '99',
        actual_price: '100',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '66',
        item_image: 'item-category/earphones/boat earphone-50.jpeg',
        item_info: 'Boat Earphone Pack of 2',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '99',
        actual_price: '100',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '67',
        item_image: 'item-category/earphones/akg-earphone.jpeg',
        item_info: 'AKG Earphone high Quality Pack of 1',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '109',
        actual_price: '220',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '68',
        item_image: 'item-category/earphones/earphone-100.jpeg',
        item_info: 'Boat high Quality bass Pack of 1',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '99',
        actual_price: '200',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '69',
        item_image: 'item-category/earphones/realme earphone.jpeg',
        item_info: 'Realme High Quality Bass Earphone',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '99',
        actual_price: '200',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '70',
        item_image: 'item-category/earphones/type-c earphone.jpeg',
        item_info: 'Type-C High Super Earphone',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '99',
        actual_price: '250',
        discount: '60',
        delivery: '00',
        offer: 'Bank Offer'
    },

]