const lights = [
    {
        id: '01',
        item_image: 'item-category/lights/ball-light.webp',
        item_info: 'FAST CHARGING 65W DATACABLE WITH 6 MONTH WARRANTY',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '149',
        actual_price: '250',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '01',
        item_image: 'item-category/lights/cliplight.webp',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '179',
        actual_price: '300',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '01',
        item_image: 'item-category/lights/colorbulb1.webp',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '39',
        actual_price: '60',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '01',
        item_image: 'item-category/lights/colorbulb2.webp',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '79',
        actual_price: '120',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '01',
        item_image: 'item-category/lights/colorbulb3.webp',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '119',
        actual_price: '200',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '01',
        item_image: 'item-category/lights/colorstarlight.webp',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '279',
        actual_price: '3000',
        discount: '90',
        delivery: '40',
        offer: 'Bank Offer'
    },
    {
        id: '01',
        item_image: 'item-category/lights/torch-129.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '149',
        actual_price: '250',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '01',
        item_image: 'item-category/lights/glass light.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '249',
        actual_price: '350',
        discount: '30',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '01',
        item_image: 'item-category/lights/wall-solar light -2.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '249',
        actual_price: '350',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '01',
        item_image: 'item-category/lights/wall-solar-light.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '229',
        actual_price: '350',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
]