const lights = [
    {
        id: '93',
        item_image: 'item-category/lights/ball-light.webp',
        item_info: 'Crystal Ball LED Lights ',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '169',
        actual_price: '250',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '94',
        item_image: 'item-category/lights/cliplight.webp',
        item_info: 'Clip Hanging LED Lights',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '179',
        actual_price: '300',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '95',
        item_image: 'item-category/lights/colorbulb1.webp',
        item_info: 'Disco Mulitcolor Bulb',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '39',
        actual_price: '60',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '96',
        item_image: 'item-category/lights/colorbulb2.webp',
        item_info: 'Disco Mulitcolor Round Bulb',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '79',
        actual_price: '120',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '97',
        item_image: 'item-category/lights/colorbulb3.webp',
        item_info: 'Disco Mulitcolor Golden Round Bulb',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '119',
        actual_price: '200',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '98',
        item_image: 'item-category/lights/colorstarlight.webp',
        item_info: 'Multicolor Star 6+6 Lights',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '279',
        actual_price: '3000',
        discount: '90',
        delivery: '40',
        offer: 'Bank Offer'
    },
    {
        id: '99',
        item_image: 'item-category/lights/starlight-warm.webp',
        item_info: 'Warm-White Color Star 6+6 Lights',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '259',
        actual_price: '3000',
        discount: '90',
        delivery: '40',
        offer: 'Bank Offer'
    },
    {
        id: '100',
        item_image: 'item-category/lights/bottlelight.webp',
        item_info: 'Pack of 4',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '129',
        actual_price: '250',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '101',
        item_image: 'item-category/lights/diya-12.webp',
        item_info: 'Pack of 12',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '149',
        actual_price: '250',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '102',
        item_image: 'item-category/lights/heart-light.jpg',
        item_info: '6+6 Warm white lights Pack of 1',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '249',
        actual_price: '350',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '103',
        item_image: 'item-category/lights/diya-light.webp',
        item_info: '6+6 Warm white lights Pack of 1',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '249',
        actual_price: '350',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '104',
        item_image: 'item-category/lights/led glu strip.webp',
        item_info: 'Multicolor lights Pack of 1',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '229',
        actual_price: '350',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '105',
        item_image: 'item-category/lights/patta light-12ft.webp',
        item_info: '12ft Multicolor running lights Pack of 1',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '249',
        actual_price: '350',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '106',
        item_image: 'item-category/lights/starlight-warm.webp',
        item_info: '6+6 Warm White lights Pack of 1',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '249',
        actual_price: '350',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '107',
        item_image: 'item-category/lights/swastik-light.webp',
        item_info: '6+6 Warm White lights Pack of 1',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '249',
        actual_price: '350',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    
    
    {
        id: '108',
        item_image: 'item-category/lights/glass light.jpeg',
        item_info: 'Crystal Glass Touch Color Changin light',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '249',
        actual_price: '350',
        discount: '30',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '109',
        item_image: 'item-category/lights/wall-solar light -2.jpeg',
        item_info: 'Wall Solar Lights Best Quality(Pack of 1)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '249',
        actual_price: '350',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '110',
        item_image: 'item-category/lights/wall-solar-light.jpeg',
        item_info: 'Wall Solar Lights  (Pack of 1)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '229',
        actual_price: '350',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '111',
        item_image: 'item-category/lights/torch-129.jpeg',
        item_info: 'High Beam Light (pack of 1)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '149',
        actual_price: '250',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
]