const mobilephones = [
    {
        id: '86',
        item_image: 'item-category/mobilephones/sam-B310 E.jpeg',
        item_info: 'Samsung B-310E Mobile with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '1199',
        actual_price: '1600',
        discount: '30',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '87',
        item_image: 'item-category/mobilephones/sam-guru-1200.jpeg',
        item_info: 'Samsung Guru 1200 Single Sim (Without Warranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '899',
        actual_price: '1400',
        discount: '30',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '88',
        item_image: 'item-category/mobilephones/sam-keytone-2 guru.jpeg',
        item_info: 'Samsung Guru1200 Keytone Single sim (6 Month Warranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '999',
        actual_price: '1400',
        discount: '30',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '89',
        item_image: 'item-category/mobilephones/nokia.jpeg',
        item_info: 'Nokia 105 Single Sim UPI Inbuilt (1 Year Warranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '1399',
        actual_price: '1600',
        discount: '30',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '90',
        item_image: 'item-category/mobilephones/nokia 105.jpeg',
        item_info: 'Nokia 105 Dual Sim UPI Inbuilt (1 Year Warranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '1499',
        actual_price: '1800',
        discount: '30',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '91',
        item_image: 'item-category/mobilephones/jio phone.jpeg',
        item_info: 'Jio Phone with 6 Month Warranty',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '999',
        actual_price: '1200',
        discount: '20',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '92',
        item_image: 'item-category/mobilephones/flip phone.jpeg',
        item_info: 'Flip Keypad Mobile (without Warranty)',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '1599',
        actual_price: '2000',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
]