const mobilephones = [
    {
        id: '01',
        item_image: 'item-category/mobilephones/sam-B310 E.jpeg',
        item_info: 'FAST CHARGING 65W DATACABLE WITH 6 MONTH WARRANTY',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '1199',
        actual_price: '1600',
        discount: '30',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '01',
        item_image: 'item-category/mobilephones/sam-guru-1200.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '700',
        actual_price: '1000',
        discount: '30',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '01',
        item_image: 'item-category/mobilephones/sam-keytone-2 guru.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '999',
        actual_price: '1400',
        discount: '30',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '01',
        item_image: 'item-category/mobilephones/nokia.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '1349',
        actual_price: '1600',
        discount: '20',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '01',
        item_image: 'item-category/mobilephones/nokia 105.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '1399',
        actual_price: '1800',
        discount: '20',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '01',
        item_image: 'item-category/mobilephones/jio phone.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '999',
        actual_price: '1200',
        discount: '20',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '01',
        item_image: 'item-category/mobilephones/flip phone.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '1399',
        actual_price: '1600',
        discount: '20',
        delivery: '00',
        offer: 'Bank Offer'
    },
]