const mobilecovers = [
    {
        id: '71',
        item_image: 'item-category/mobilecover/6dcover.jpeg',
        item_info: '(Pack of 2)6D Imported Mobile Cover ',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '99',
        actual_price: '100',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '72',
        item_image: 'item-category/mobilecover/doll.jpeg',
        item_info: 'Female Mobile Cover',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '129',
        actual_price: '250',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '73',
        item_image: 'item-category/mobilecover/flip-cover.webp',
        item_info: 'Imported Mobile Flip Cover',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '99',
        actual_price: '150',
        discount: '30',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '74',
        item_image: 'item-category/mobilecover/metalringcover.jpeg',
        item_info: 'Metal Ring Imported Mobile Cover',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '149',
        actual_price: '300',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '75',
        item_image: 'item-category/mobilecover/puffcover.jpeg',
        item_info: '(Pack of 2)Puff Mobile Cover',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '150',
        actual_price: '100',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '76',
        item_image: 'item-category/mobilecover/socool.jpeg',
        item_info: 'So-Cool Imported shiny Mobile Cover',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '80',
        actual_price: '100',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },

]