const mobilestands = [
    {
        id: '77',
        item_image: 'item-category/mobilestand/mobile plug holder.webp',
        item_info: '(Pack of 2) Mobile Charging Stand',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '149',
        actual_price: '300',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '78',
        item_image: 'item-category/mobilestand/mobile premium stand.webp',
        item_info: 'Imported Mobile Stand',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '129',
        actual_price: '250',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '79',
        item_image: 'item-category/mobilestand/mobile round stand.jpeg',
        item_info: 'metalic Round Mobile Stand High Strenth',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '149',
        actual_price: '300',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '80',
        item_image: 'item-category/mobilestand/mobilestand20.jpeg',
        item_info: 'Mobile Stand Non-Metalic',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '29',
        actual_price: '60',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '81',
        item_image: 'item-category/mobilestand/selfie stand with light.jpeg',
        item_info: 'Selfie Stick with light',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '189',
        actual_price: '300',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '82',
        item_image: 'item-category/mobilestand/selfie stand without light.webp',
        item_info: 'Selfie Stick without light',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '169',
        actual_price: '250',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '83',
        item_image: 'item-category/mobilestand/triangle stnad.jpeg',
        item_info: '3-Shape Triangle Mobile Stand',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '15',
        actual_price: '30',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
]