const mobilecovers = [
    {
        id: '01',
        item_image: 'item-category/mobilecover/6dcover.jpeg',
        item_info: 'FAST CHARGING 65W DATACABLE WITH 6 MONTH WARRANTY',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '60',
        actual_price: '100',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '01',
        item_image: 'item-category/mobilecover/doll.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '119',
        actual_price: '180',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '01',
        item_image: 'item-category/mobilecover/flip-cover.webp',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '99',
        actual_price: '150',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '01',
        item_image: 'item-category/mobilecover/metalringcover.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '129',
        actual_price: '200',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '01',
        item_image: 'item-category/mobilecover/puffcover.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '80',
        actual_price: '100',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '01',
        item_image: 'item-category/mobilecover/socool.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '80',
        actual_price: '100',
        discount: '90',
        delivery: '00',
        offer: 'Bank Offer'
    },

]