const smartgadgets = [
    {
        id: '01',
        item_image: 'item-category/smartgadgets/cable protector.jpeg',
        item_info: 'Cable Protector Pack of 3',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '50',
        actual_price: '3000',
        discount: '90',
        delivery: '40',
        offer: 'Bank Offer'
    },
    {
        id: '01',
        item_image: 'item-category/smartgadgets/connector1.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '59',
        actual_price: '100',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '01',
        item_image: 'item-category/smartgadgets/connectors4.webp',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '199',
        actual_price: '350',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '01',
        item_image: 'item-category/smartgadgets/dancing cactus.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '249',
        actual_price: '350',
        discount: '30',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '01',
        item_image: 'item-category/smartgadgets/drone.webp',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '1499',
        actual_price: '3000',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '01',
        item_image: 'item-category/smartgadgets/hairdrier.webp',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '299',
        actual_price: '400',
        discount: '30',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '01',
        item_image: 'item-category/smartgadgets/k9 mic.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '329',
        actual_price: '500',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '01',
        item_image: 'item-category/smartgadgets/led usb bulb.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '15',
        actual_price: '30',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '01',
        item_image: 'item-category/smartgadgets/mini projector.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '1499',
        actual_price: '3000',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '01',
        item_image: 'item-category/smartgadgets/moscuto bat-2.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '249',
        actual_price: '500',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '01',
        item_image: 'item-category/smartgadgets/otg 30.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '29',
        actual_price: '60',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '01',
        item_image: 'item-category/smartgadgets/otg-50.webp',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '49',
        actual_price: '100',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '01',
        item_image: 'item-category/smartgadgets/pen stand.jpeg',
        item_info: 'Pen Stand & Writing Pack of 3',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '49',
        actual_price: '100',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '01',
        item_image: 'item-category/smartgadgets/plug hub -10 pin.webp',
        item_info: 'Lady Jointer 10-Pin Switch',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '129',
        actual_price: '200',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '01',
        item_image: 'item-category/smartgadgets/plug hub combo.webp',
        item_info: 'Lady Jointer 10-Pin Switch Pack of 2',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '200',
        actual_price: '300',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '01',
        item_image: 'item-category/smartgadgets/pubg thumb.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '10',
        actual_price: '20',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '01',
        item_image: 'item-category/smartgadgets/sim ejector.jpeg',
        item_info: 'Sim Ejector Pack of 10',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '29',
        actual_price: '100',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '01',
        item_image: 'item-category/smartgadgets/torch mulitpurpose.jpeg',
        item_info: 'Multipurpose Torch',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '149',
        actual_price: '250',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '01',
        item_image: 'item-category/smartgadgets/treamer.jpeg',
        item_info: 'Vintage Treamer Super Quality',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '279',
        actual_price: '500',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '01',
        item_image: 'item-category/smartgadgets/usbhub.webp',
        item_info: '4 in 1 USB Hub Connector Super Quality',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '179',
        actual_price: '300',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '01',
        item_image: 'item-category/smartgadgets/v8 to type c.jpeg',
        item_info: 'V8 to Type-C Connector pack of 1',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '25',
        actual_price: '50',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '01',
        item_image: 'item-category/smartgadgets/vaccumcleaner.webp',
        item_info: 'Vaccum Cleaner Pack of 1',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '279',
        actual_price: '500',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '01',
        item_image: 'item-category/smartgadgets/water bottle temperature.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '199',
        actual_price: '350',
        discount: '30',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '01',
        item_image: 'item-category/smartgadgets/wireless blutooth-2.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '79',
        actual_price: '120',
        discount: '30',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '01',
        item_image: 'item-category/smartgadgets/writing pad.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '89',
        actual_price: '150',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },


]