const smartwatches = [
    {
        id: '42',
        item_image: 'item-category/smartwatch/firebolt-1.jpeg',
        item_info: 'FAST CHARGING 65W DATACABLE WITH 6 MONTH WARRANTY',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '300',
        actual_price: '3000',
        discount: '90',
        delivery: '40',
        offer: 'Bank Offer'
    },
    {
        id: '43',
        item_image: 'item-category/smartwatch/firebolt-2.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '300',
        actual_price: '3000',
        discount: '90',
        delivery: '40',
        offer: 'Bank Offer'
    },
    {
        id: '44',
        item_image: 'item-category/smartwatch/s8 watch.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '300',
        actual_price: '3000',
        discount: '90',
        delivery: '40',
        offer: 'Bank Offer'
    },
    {
        id: '45',
        item_image: 'item-category/smartwatch/series 9 watch.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '300',
        actual_price: '3000',
        discount: '90',
        delivery: '40',
        offer: 'Bank Offer'
    },
    {
        id: '46',
        item_image: 'item-category/smartwatch/t-10 ulta.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '300',
        actual_price: '3000',
        discount: '90',
        delivery: '40',
        offer: 'Bank Offer'
    },
    {
        id: '47',
        item_image: 'item-category/smartwatch/t800 ultra.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '300',
        actual_price: '3000',
        discount: '90',
        delivery: '40',
        offer: 'Bank Offer'
    },
    {
        id: '48',
        item_image: 'item-category/smartwatch/smartwatch-180.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '300',
        actual_price: '3000',
        discount: '90',
        delivery: '40',
        offer: 'Bank Offer'
    },


]