const smartwatches = [
    {
        id: '42',
        item_image: 'item-category/smartwatch/firebolt-1.jpeg',
        item_info: 'ForeBolt Smart Watch',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '849',
        actual_price: '1300',
        discount: '35',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '43',
        item_image: 'item-category/smartwatch/firebolt-2.jpeg',
        item_info: 'ForeBolt Smart Watch Round Dial',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '949',
        actual_price: '1500',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '44',
        item_image: 'item-category/smartwatch/s8 watch.jpeg',
        item_info: 'S-8 Smart Watch',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '399',
        actual_price: '600',
        discount: '30',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '45',
        item_image: 'item-category/smartwatch/series 9 watch.jpeg',
        item_info: 'S-9 Series Smart Watch',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '449',
        actual_price: '800',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '46',
        item_image: 'item-category/smartwatch/t-10 ulta.jpeg',
        item_info: 'T-10 Ulta Smart Watch',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '599',
        actual_price: '900',
        discount: '35',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '47',
        item_image: 'item-category/smartwatch/t800 ultra.jpeg',
        item_info: 'T-800 Ultra Smart Watch',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '499',
        actual_price: '1000',
        discount: '50',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '48',
        item_image: 'item-category/smartwatch/smartwatch-180.jpeg',
        item_info: 'Smart Bracelet Watch',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '219',
        actual_price: '300',
        discount: '30',
        delivery: '00',
        offer: 'Bank Offer'
    },


]