const speakers = [
    {
        id: '49',
        item_image: 'item-category/speakers/tyre-speaker.jpeg',
        item_info: 'FAST CHARGING 65W DATACABLE WITH 6 MONTH WARRANTY',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '300',
        actual_price: '3000',
        discount: '90',
        delivery: '40',
        offer: 'Bank Offer'
    },

    {
        id: '50',
        item_image: 'item-category/speakers/halozan.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '300',
        actual_price: '3000',
        discount: '90',
        delivery: '40',
        offer: 'Bank Offer'
    },
    {
        id: '51',
        item_image: 'item-category/speakers/light sound bulb.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '300',
        actual_price: '3000',
        discount: '90',
        delivery: '40',
        offer: 'Bank Offer'
    },
    {
        id: '52',
        item_image: 'item-category/speakers/minispeaker.webp',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '300',
        actual_price: '3000',
        discount: '90',
        delivery: '40',
        offer: 'Bank Offer'
    },
    {
        id: '53',
        item_image: 'item-category/speakers/mz soundbar.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '300',
        actual_price: '3000',
        discount: '90',
        delivery: '40',
        offer: 'Bank Offer'
    },

    {
        id: '54',
        item_image: 'item-category/speakers/mz-soundbar-2.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '300',
        actual_price: '3000',
        discount: '90',
        delivery: '40',
        offer: 'Bank Offer'
    },
    {
        id: '55',
        item_image: 'item-category/speakers/disco-speaker.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '300',
        actual_price: '3000',
        discount: '90',
        delivery: '40',
        offer: 'Bank Offer'
    },

    {
        id: '56',
        item_image: 'item-category/speakers/mzspeaker-2.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '300',
        actual_price: '3000',
        discount: '90',
        delivery: '40',
        offer: 'Bank Offer'
    },
    {
        id: '57',
        item_image: 'item-category/speakers/mzspeaker-3.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '300',
        actual_price: '3000',
        discount: '90',
        delivery: '40',
        offer: 'Bank Offer'
    },

    {
        id: '58',
        item_image: 'item-category/speakers/mzspeaker.webp',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '300',
        actual_price: '3000',
        discount: '90',
        delivery: '40',
        offer: 'Bank Offer'
    },
    {
        id: '59',
        item_image: 'item-category/speakers/speaker mic sound.jpeg',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '300',
        actual_price: '3000',
        discount: '90',
        delivery: '40',
        offer: 'Bank Offer'
    },
    {
        id: '60',
        item_image: 'item-category/speakers/woodspeaker.webp',
        item_info: 'Men Printed Round Neck Polyester Black T-Shirt',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '300',
        actual_price: '3000',
        discount: '90',
        delivery: '40',
        offer: 'Bank Offer'
    },
]