const speakers = [
    {
        id: '49',
        item_image: 'item-category/speakers/tyre-speaker.jpeg',
        item_info: 'Smart & Unique Tyre Speaker with LED',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '649',
        actual_price: '900',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },

    {
        id: '50',
        item_image: 'item-category/speakers/halozan.jpeg',
        item_info: 'Advertise Loud Speaker',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '459',
        actual_price: '600',
        discount: '25',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '51',
        item_image: 'item-category/speakers/light sound bulb.jpeg',
        item_info: 'LED Buld with Sound',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '299',
        actual_price: '450',
        discount: '40',
        delivery: '40',
        offer: 'Bank Offer'
    },
    {
        id: '52',
        item_image: 'item-category/speakers/minispeaker.webp',
        item_info: 'Mini High Bass Speaker',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '249',
        actual_price: '400',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '53',
        item_image: 'item-category/speakers/mz soundbar.jpeg',
        item_info: 'Wound Bar with LED light',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '529',
        actual_price: '700',
        discount: '30',
        delivery: '00',
        offer: 'Bank Offer'
    },

    {
        id: '54',
        item_image: 'item-category/speakers/mz-soundbar-2.jpeg',
        item_info: 'MZ Sound with high Quality bass',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '549',
        actual_price: '800',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '55',
        item_image: 'item-category/speakers/disco-speaker.jpeg',
        item_info: 'Disco Light Speaker',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '289',
        actual_price: '400',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },

    {
        id: '56',
        item_image: 'item-category/speakers/mzspeaker-2.jpeg',
        item_info: 'MZ Speaker with light',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '279',
        actual_price: '400',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '57',
        item_image: 'item-category/speakers/mzspeaker-3.jpeg',
        item_info: 'MZ Speaker High Bass with light',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '299',
        actual_price: '450',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },

    {
        id: '58',
        item_image: 'item-category/speakers/mzspeaker.webp',
        item_info: 'MZ Speaker High Bass with light',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '289',
        actual_price: '400',
        discount: '25',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '59',
        item_image: 'item-category/speakers/speaker mic sound.jpeg',
        item_info: 'Metal Sound with Mic high quality',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '599',
        actual_price: '850',
        discount: '30',
        delivery: '00',
        offer: 'Bank Offer'
    },
    {
        id: '60',
        item_image: 'item-category/speakers/woodspeaker.webp',
        item_info: 'Wooden Speaker',
        seller: 'Harry',
        delivery_date: '15-06-2024',
        rating: '4.5',
        current_price: '279',
        actual_price: '400',
        discount: '40',
        delivery: '00',
        offer: 'Bank Offer'
    },
]